/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2019 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/


const char html_page_reboot[] PROGMEM = 
"<p>Rebooting... Refresh in <span id='count'>10s</span>...</p>"
;

const char html_page_reset[] PROGMEM = 
"<p>Resetting... Connect to SSID HVAC_XXXX...</p>"
;


const char html_page_save_reboot[] PROGMEM = 
"<p>Saving configuration and rebooting... Refresh in <span id='count'>10s</span>...</p>"
;

const char html_page_mqtt[] PROGMEM = 
"<h2>Config</h2>"
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp;MQTT Parameters&nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>Friendly name</b>"
                "<br/>"
                "<input id='fn' name='fn' placeholder=' ' value='_UNIT_NAME_'>"
            "</p>"
            "<p><b>Host</b> ()"
                "<br/>"
                "<input id='mh' name='mh' placeholder=' ' value='_MQTT_HOST_'>"
            "</p>"
            "<p><b>Port</b> (default 1883)"
                "<br/>"
                "<input id='ml' name='ml' placeholder='1883' value='_MQTT_PORT_'>"
            "</p>"
            "<p><b>User</b>"
                "<br/>"
                "<input id='mu' name='mu' placeholder='DVES_USER' value='_MQTT_USER_'>"
            "</p>"
            "<p><b>Password</b>"
                "<br/>"
                "<input id='mp' name='mp' type='password' placeholder='Password' value='_MQTT_PASSWORD_'>"
            "</p>"
            "<p><b>Topic</b>"
                "<br/>"
                "<input id='mt' name='mt' placeholder='topic' value='_MQTT_TOPIC_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_others[] PROGMEM = 
"<h2>Config</h2>"
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp;Others Parameters&nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>HA Autodiscovery</b>"
                "<select name='HAA'>"
                    "<option value='ON' _HAA_ON_>ON</option>"
                    "<option value='OFF' _HAA_OFF_>OFF</option>"
                "</select>"
            "</p>"
            "<p><b>Home Assistant Autodiscovery topic</b> ()"
                "<br/>"
                "<input id='haat' name='haat' placeholder=' ' value='_HAA_TOPIC_'>"
            "</p>"
            "<p><b>Debug</b>"
                "<select name='Debug'>"
                    "<option value='ON' _DEBUG_ON_>ON</option>"
                    "<option value='OFF' _DEBUG_OFF_>OFF</option>"
                "</select>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_status[] PROGMEM = 
"<h2>Status</h2>"
"<div id='l1' name='l1'>"
    "HVAC Status => _HVAC_STATUS_"
    "<br /> MQTT Status => _MQTT_STATUS_ ( _MQTT_REASON_ )"
    "<br /> WIFI Rssi => _WIFI_STATUS_ dBm"
    "<br />"
    "<p>"
        "<a class='button back' href='/'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_wifi[] PROGMEM = 
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp;WIFI Parameters&nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>Hostname</b>"
                "<br/>"
                "<input id='hn' name='hn' placeholder=' ' value='_UNIT_NAME_'>"
            "</p>"
            "<p><b>SSID</b> ()"
                "<br/>"
                "<input id='ssid' name='ssid' placeholder=' ' value='_SSID_'>"
            "</p>"
            "<p><b>Password</b> ()"
                "<br/>"
                "<input id='psk' name='psk' placeholder=' ' value='_PSK_'>"
            "</p>"
            "<p><b>OTA Password</b>"
                "<br/>"
                "<input id='otapwd' name='otapwd' placeholder=' ' value='_OTA_PWD_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_advance[] PROGMEM = 
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp;Advanced configuration&nbsp;</b></legend>"
        "<form method='post'>"
            "<p>"
                "<b>Temperature Unit</b>"
                "<select name='tu'>"
                    "<option value='cel' _TU_CEL_>° Celsius</option>"
                    "<option value='fah' _TU_FAH_>° Fahrenheit</option>"
                "</select>"
            "</p>"
            "<p><b>Ninimum temperture</b>"
                "<br/>"
                "<input type='number' id='min_temp' name='min_temp' placeholder=' ' value='_MIN_TEMP_'>"
            "</p>"
            "<p><b>Maximum temperture</b>"
                "<br/>"
                "<input type='number' id='max_temp' name='max_temp' placeholder=' ' value='_MAX_TEMP_'>"
            "</p>"
            "<p><b>Temperture step</b>"
                "<br/>"
                "<input type='number' id='temp_step' step='0.1' name='temp_step' placeholder=' ' value='_TEMP_STEP_'>"
            "</p>"
            "<p>"
                "<b>Mode Support</b>"
                "<select name='md'>"
                    "<option value='all' _MD_ALL_>All mode</option>"
                    "<option value='nht' _MD_NONHEAT_>Not support heat mode</option>"
                "</select>"
            "</p>"
            "<p><b>Login Password</b>"
                "<br/>"
                "<input id='lpw' name='lpw' type='password' placeholder=' ' value='_LOGIN_PASSWORD_'>"
            "</p>"
            "<p>Note: Default login user is <b>admin</b></p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button' href='/setup' class='back'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_login[] PROGMEM = 
"<script>"
    "var loginSucess = _LOGIN_SUCCESS_;"
    "document.onreadystatechange = function() {"
        "if (document.readyState === 'complete') {"
            "if (loginSucess == 1) {"
                "var element = document.getElementById('login_form');"
                "element.parentNode.removeChild(element);"
            "}"
        "}"
    "}"
"</script>"
"<div id='login_form' name='login_form'>"
    "<fieldset>"
        "<legend><b>&nbsp;LOGIN&nbsp;</b></legend>"
        "<form action='/login' method='post'>"
            "<p>To log in, enter user: <b>admin</b> and password</p>"
            "<p><b>User</b>"
                "<input type='text' name='USERNAME' placeholder='user name'>"
            "</p>"
            "<p><b>Password</b>"
                "<input type='password' name='PASSWORD' placeholder='password'>"
            "</p>"
            "<br/>"
            "<button name='SUBMIT' type='submit' class='button bgrn'>SUBMIT</button>"
        "</form>"
        "<br> You can go to <a href='/status'>status page</a>"
        "<br>"
    "</fieldset>"
"</div>"
"<div>"
    "_LOGIN_MSG_"
"</div>"
;

const char html_page_upgrade[] PROGMEM = 
"<script>"
    "function eb(s) {"
        "return document.getElementById(s);"
    "}"
"</script>"
    "<div id='f1' style='display:block;'>"
        "<fieldset>"
            "<legend><b>&nbsp;Firmware OTA upgrade by bin file upload&nbsp;</b></legend>"
            "<form method='post' action='upload' enctype='multipart/form-data'>"
                "<br>"
                "<input type='file' accept='.bin' name='upload'>"
                "<br>"
                "<br>"
                "<button type='submit' onclick=\"eb('f1').style.display='none';eb('f2').style.display='block';this.form.submit();\" class='button bgrn'>Start upgrade</button>"
            "</form>"
        "</fieldset>"
        "<p>"
            "<a class='button back' href='/'>Back</a>"
        "</p>"
    "</div>"
    "<div id='f2' style='display:none;text-align:center;'><b>Upload started ...</b></div>"
;


const char html_page_upload[] PROGMEM = 
"<div id='l1' name='l1'>"
    "<br>_UPLOAD_MSG_"
    "<p>"
        "<a class='button back' href='/upgrade'>Back</a>"
    "</p>"
"</div>"
;
